# Generated by Django 2.2.27 on 2022-04-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='ToDoList',
        ),
    ]
