# Generated by Django 2.2.27 on 2022-05-01 15:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220426_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[main.models.validate_extension]),
        ),
    ]
