# Generated by Django 2.2.27 on 2022-05-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
